name: m7_livelyness_detection
description: A single function package to detect weather the face visible in the camera is a live face or not.
version: 0.0.2+2
homepage: https://github.com/Meet-7-dating/m7_livelyness_detection
repository: https://github.com/Meet-7-dating/m7_livelyness_detection/
issue_tracker: https://github.com/Meet-7-dating/m7_livelyness_detection/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: ^3.0.2
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.5.0
  lottie: ^2.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.m7_livelyness_detection
        pluginClass: M7LivelynessDetectionPlugin
      ios:
        pluginClass: M7LivelynessDetectionPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-start.json
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-success.json
    - packages/m7_livelyness_detection/src/assets/lottie/step_completed.json